#!/bin/bash

export AZEROTHCORE_SOURCE_DIR=azerothcore
export AZEROTHCORE_SERVER_DIR=azerothcore-server
export AZEROTHCORE_SERVER_BACKUPS_DIR=azerothcore-server-backups
export AZEROTHCORE_SERVER_REMOTE_ENDPOINT=127.0.0.1
export AZEROTHCORE_SERVER_BIND_IP=127.0.0.1
export AZEROTHCORE_SERVER_LOCAL_SUBNETMASK=255.255.255.0
export WHERE_WAS_I=$(pwd)
